// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { SessionProvider } from "next-auth/react";
// import "./globals.css";
// import { getServerSession } from "next-auth";
// import NavMenu from "@/components/NavMenu";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default  function RootLayout({
//   children
// }: {
//   children: React.ReactNode;
// }) {
//   const session =  getServerSession();
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SessionProvider session={session}>
//           <main className="mx-auto max-w-5xl text-2xl flex gap-2 text-white">
//             <NavMenu />
//             {children}
//           </main>
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }


import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';
// Components
import ProviderWrapper from './ProviderWrapper';
// Styles
import "./globals.css";

const RootLayout = async ({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children
}: {
  children: React.ReactNode;
}) => {
  const session = await getServerSession();

  if (!session) redirect('/api/auth/signin');

  return (
    <html lang='en'>
      <body >
        <ProviderWrapper session={session}>{children}</ProviderWrapper>
      </body>
    </html>
  );
};

export default RootLayout;